echo "[Autoconnect Wifi]"
sh -c "sudo echo \"network:\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"    ethernets:\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"        eth0:\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"            dhcp4: true\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"            optional: true\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"    version: 2\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"    wifis:\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"        rendered: networkd\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"        wlan0:\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"            dhcp4: true\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"            optional: true\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"            access-points:\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"                \"Irbot_slam:\"\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"                    password: \"1234567890\"\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"        wlan0:\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"            dhcp4: true\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"            optional: true\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"            access-points:\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"                \"River:\"\" >> /etc/netplan/50-cloud-init.yaml"
sh -c "sudo echo \"                    password: \"tothemoooon\"\" >> /etc/netplan/50-cloud-init.yaml"

sudo netplan generate
sudo netplan apply
